
name: Test DRF Savannah Informatics API

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd project
        
        # Set TEST_DATABASE_PREFIX variable to an empty string if it is None
        TEST_DATABASE_PREFIX="${TEST_DATABASE_PREFIX:-}"

        # Concatenate TEST_DATABASE_PREFIX and database name, handling None case
        DB_NAME="${TEST_DATABASE_PREFIX}${DB_NAME}"

        python manage.py test
